import type { LearningPack, PackRequest } from "./concept-types";

/** Renders a learning pack as portable Markdown for copy / download. */
export function packToMarkdown(pack: LearningPack, request: PackRequest): string {
  const lines: string[] = [];
  lines.push(`# ${request.topic}`);
  lines.push("");
  lines.push(`_Level: ${request.level} · Analogy: ${request.analogyStyle} · Language: ${request.language}_`);
  lines.push("");
  lines.push("## TL;DR");
  lines.push(pack.tldr);
  lines.push("");
  lines.push("## Explanation");
  pack.explanation.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
  lines.push("");
  lines.push("## Analogy");
  lines.push(pack.analogy);
  lines.push("");
  if (pack.code) {
    lines.push("## Code example");
    lines.push("```" + pack.code.language.toLowerCase());
    lines.push(pack.code.snippet);
    lines.push("```");
    if (pack.code.explanation) lines.push(pack.code.explanation);
    lines.push("");
  }
  lines.push("## Common misconceptions");
  pack.misconceptions.forEach((m) => lines.push(`- ${m}`));
  lines.push("");
  lines.push("## Key takeaways");
  pack.takeaways.forEach((t) => lines.push(`- ${t}`));
  lines.push("");
  lines.push("## Quiz");
  pack.quiz.forEach((q, i) => {
    lines.push(`${i + 1}. ${q.question}`);
    q.options.forEach((o, oi) =>
      lines.push(`   ${String.fromCharCode(65 + oi)}. ${o}${oi === q.correctIndex ? "  ✅" : ""}`),
    );
    if (q.explanation) lines.push(`   > ${q.explanation}`);
  });
  lines.push("");
  lines.push("## Flashcards");
  pack.flashcards.forEach((c) => lines.push(`- **${c.front}** — ${c.back}`));
  lines.push("");
  lines.push("---");
  lines.push("Generated by Concept Coach. AI can be wrong — verify anything important.");
  return lines.join("\n");
}

export function downloadMarkdown(filename: string, contents: string) {
  const blob = new Blob([contents], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}
